name: biascon
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.2=py37h2d18471_0
  - numpy-base=1.20.2=py37hfae3a4d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.1.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu110
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - backcall==0.2.0
    - chardet==4.0.0
    - click==8.0.1
    - configparser==5.0.2
    - decorator==5.0.9
    - docker-pycreds==0.4.0
    - gitdb==4.0.7
    - gitpython==3.1.17
    - idna==2.10
    - importlib-metadata==4.5.0
    - ipdb==0.13.9
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - matplotlib-inline==0.1.2
    - pandas==1.2.4
    - parso==0.8.2
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - promise==2.3
    - prompt-toolkit==3.0.18
    - protobuf==3.17.2
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - sentry-sdk==1.1.0
    - shortuuid==1.0.1
    - smmap==4.0.0
    - subprocess32==3.5.4
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - tqdm==4.61.0
    - traitlets==5.0.5
    - urllib3==1.26.5
    - wandb==0.10.31
    - wcwidth==0.2.5
    - zipp==3.4.1